# Generated by Django 4.0.5 on 2022-06-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0003_alter_userprofile_checker_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='checker_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mahid_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='maker1time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='maker2time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='needed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='request_date',
            field=models.DateTimeField(null=True),
        ),
    ]
