# Generated by Django 4.0.5 on 2022-07-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0005_alter_userprofile_checker_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='etd',
            field=models.DateTimeField(null=True),
        ),
    ]
