# Generated by Django 4.0.5 on 2022-08-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0007_alter_userprofile_acd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='task_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
