# Generated by Django 4.1.1 on 2022-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0008_userprofile_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
