# Generated by Django 4.1.1 on 2022-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0012_userprofile_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='etd',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
