# Generated by Django 4.1.1 on 2022-09-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0014_alter_userprofile_urgent_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
