# Generated by Django 4.1.1 on 2022-09-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0015_alter_userprofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
