# Generated by Django 4.1.1 on 2022-09-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0016_alter_userprofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='request_date',
            field=models.DateTimeField(null=True),
        ),
    ]
