# Generated by Django 4.1.1 on 2022-09-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0017_alter_userprofile_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoupdate',
            name='update_date',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
