# Generated by Django 4.1.1 on 2022-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0018_infoupdate_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='checker_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastupdate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mahid_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='maker1time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='maker2time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prog',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='task_details',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acd',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='add_to_google',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='etd',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='needed_date',
            field=models.DateTimeField(max_length=30, null=True),
        ),
    ]
