# Generated by Django 4.1.1 on 2022-09-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0020_alter_userprofile_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoupdate',
            name='latest_update',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
