# Generated by Django 4.1.1 on 2022-09-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0021_alter_infoupdate_latest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attachment',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comment',
            field=models.DateTimeField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
