# Generated by Django 4.1.1 on 2022-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0022_userprofile_attachment_userprofile_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='attachment',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comment',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
