# Generated by Django 4.1.1 on 2022-09-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0024_alter_userprofile_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
