# Generated by Django 4.1.2 on 2022-10-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0025_alter_userprofile_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
