# Generated by Django 4.1.2 on 2022-10-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0026_userprofile_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='maker1',
            field=models.CharField(max_length=30),
        ),
    ]
