# Generated by Django 4.1.2 on 2022-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0028_alter_userprofile_maker1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_Duaration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_environtment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_privilege_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='application_project_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='why_access_needed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
