# Generated by Django 4.1.2 on 2022-12-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0029_userprofile_access_duaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Updated_task_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latest_update',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='update_date',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
