# Generated by Django 4.1.2 on 2022-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0032_rename_customerinfo_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='phonenumber',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
