# Generated by Django 4.1.2 on 2023-01-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0033_alter_companyinfo_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
