# Generated by Django 4.1.2 on 2023-01-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0034_userprofile_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_id',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
