# Generated by Django 4.1.2 on 2023-01-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_portal', '0035_alter_userprofile_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='comp_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
