# Generated by Django 4.1.2 on 2023-01-27 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0036_companyinfo_comp_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password1', models.CharField(max_length=128, null=True)),
                ('password2', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('mobile', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='mobile')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('comp_user_id', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('password1', models.CharField(max_length=128, null=True)),
                ('password2', models.CharField(max_length=16, null=True)),
                ('first_name', models.CharField(max_length=16, null=True)),
                ('last_name', models.CharField(max_length=16, null=True)),
                ('is_superuser', models.CharField(max_length=16, null=True)),
                ('is_staff', models.CharField(max_length=16, null=True)),
                ('comp_user_id', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
