# Generated by Django 4.1.2 on 2023-01-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0037_user_userreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comp_user_id',
        ),
    ]
