# Generated by Django 4.1.2 on 2023-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_portal', '0038_remove_user_comp_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comp_user_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
